# Generated by Django 3.2.22 on 2023-10-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='ededd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
